[package]
name = "nova-protocol"
description = "Wire commands and responses for Nova"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nova-types.workspace = true
thiserror.workspace = true

[lints]
workspace = true
